# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=5)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('response_avg', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pdf', models.NullBooleanField()),
                ('audit', models.NullBooleanField()),
                ('dist_req', models.CharField(choices=[('EC', 'Epistemology and Cognition'), ('EM', 'Ethical Thought and Moral Values'), ('HA', 'Historical Analysis'), ('LA', 'Literature and the Arts'), ('QR', 'Quantitative Reasoning'), ('SA', 'Social Analysis'), ('STL', 'Science and Technology with Lab'), ('STN', 'Science and Technology, no Lab')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('course_nums', models.ManyToManyField(to='api.CourseNumber')),
                ('instructors', models.ManyToManyField(to='api.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='section name is invalid', regex='^[A-Z]\\d\\d$')])),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('X', 'Canceled')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='meeting days string is invalid', regex='^M?T?W?(?:Th)?F?$')])),
                ('enrollment', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='invalid subject code', regex='[A-Z]{3}')])),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('suffix', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='suffix is invalid', regex='^(?:S|SU|F)\\d{4}$')])),
                ('name', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='invalid term name', regex='^(?:Fall|Spring|Summer) \\d{4}$')])),
                ('code', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)])),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField(unique=True)),
                ('season', models.CharField(choices=[('S', 'Spring'), ('SU', 'Summer'), ('F', 'Fall')], max_length=2)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('netid', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='offering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Term'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Offering'),
        ),
        migrations.AddField(
            model_name='coursenumber',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.CourseNumber'),
        ),
        migrations.AddField(
            model_name='advice',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Offering'),
        ),
    ]
