# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_offering_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='id',
        ),
        migrations.AddField(
            model_name='offering',
            name='guid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
