# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170101_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='evals_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "UPDATE api_course "
            "SET details_scraped = TRUE, evals_scraped = TRUE"
        ),
        migrations.AlterField(
            model_name='term',
            name='season',
            field=models.CharField(choices=[('S', 'Spring'), ('SU', 'Summer'), ('F', 'Fall')], editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
