# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pdf_only_default_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='primary_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.CourseNumber'),
        ),
    ]
