# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_section_rename_guid_to_class_id'),
    ]

    operations = [
        # http://stackoverflow.com/a/39541048/237904
        migrations.RunSQL(
            'SET CONSTRAINTS ALL IMMEDIATE;',
            migrations.RunSQL.noop),
        migrations.AddField(
            model_name='section',
            name='status_code',
            field=models.CharField(
                choices=[('O', 'Open'), ('C', 'Closed'), ('X', 'Cancelled')],
                default='O',
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "UPDATE api_section SET status_code = 'O' WHERE status = 'Open';",
            "UPDATE api_section SET status = 'Open' WHERE status_code = 'O';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET status_code = 'C' WHERE status = 'Closed';",
            "UPDATE api_section SET status = 'Closed' WHERE status_code = 'C';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET status_code = 'X' WHERE status = 'Cancelled';",
            "UPDATE api_section SET status = 'Cancelled' WHERE status_code = 'X';",
        ),
        migrations.RemoveField(
            model_name='section',
            name='status',
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            'SET CONSTRAINTS ALL IMMEDIATE;'),
    ]
