# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_section_shorten_status_field'),
    ]

    operations = [
        # http://stackoverflow.com/a/39541048/237904
        migrations.RunSQL(
            'SET CONSTRAINTS ALL IMMEDIATE;',
            migrations.RunSQL.noop),
        migrations.AddField(
            model_name='section',
            name='type_code',
            field=models.CharField(
                choices=[('C', 'Class'), ('D', 'Drill'), ('E', 'Ear training'),
                         ('F', 'Film'), ('B', 'Lab'), ('L', 'Lecture'),
                         ('P', 'Precept'), ('S', 'Seminar'), ('U', 'Studio')],
                default='L',
                max_length=1
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'C' WHERE type = 'Class';",
            "UPDATE api_section SET type = 'Class' WHERE type_code = 'C';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'D' WHERE type = 'Drill';",
            "UPDATE api_section SET type = 'Drill' WHERE type_code = 'D';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'E' WHERE type = 'Ear training';",
            "UPDATE api_section SET type = 'Ear training' WHERE type_code = 'E';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'F' WHERE type = 'Film';",
            "UPDATE api_section SET type = 'Film' WHERE type_code = 'F';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'B' WHERE type = 'Lab';",
            "UPDATE api_section SET type = 'Lab' WHERE type_code = 'B';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'L' WHERE type = 'Lecture';",
            "UPDATE api_section SET type = 'Lecture' WHERE type_code = 'L';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'P' WHERE type = 'Precept';",
            "UPDATE api_section SET type = 'Precept' WHERE type_code = 'P';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'S' WHERE type = 'Seminar';",
            "UPDATE api_section SET type = 'Seminar' WHERE type_code = 'S';",
        ),
        migrations.RunSQL(
            "UPDATE api_section SET type_code = 'U' WHERE type = 'Studio';",
            "UPDATE api_section SET type = 'Studio' WHERE type_code = 'U';",
        ),
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            'SET CONSTRAINTS ALL IMMEDIATE;'),
    ]
