# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 00:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_number_field_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='meeting days string is invalid', regex='^M?T?W?(?:Th)?F?$')])),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='course',
            new_name='offering',
        ),
        migrations.RemoveField(
            model_name='section',
            name='days',
        ),
        migrations.RemoveField(
            model_name='section',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='section',
            name='location',
        ),
        migrations.RemoveField(
            model_name='section',
            name='start_time',
        ),
        migrations.AddField(
            model_name='section',
            name='offering',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Offering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.CourseNumber'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='dist_req',
            field=models.CharField(blank=True, choices=[('EC', 'Epistemology and Cognition'), ('EM', 'Ethical Thought and Moral Values'), ('HA', 'Historical Analysis'), ('LA', 'Literature and the Arts'), ('QR', 'Quantitative Reasoning'), ('SA', 'Social Analysis'), ('STL', 'Science and Technology with Lab'), ('STN', 'Science and Technology, no Lab')], max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Section'),
        ),
    ]
