# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_section_shorten_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='enrollment',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
