# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_models_reflect_webfeeds_api_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='course_nums',
            new_name='cross_listings',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
        migrations.AddField(
            model_name='offering',
            name='primary_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.CourseNumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursenumber',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Offering'),
        ),
    ]
