# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 01:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_models_adjust_course_coursenum_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='status name is invalid', regex='^[a-zA-Z]+$')]),
        ),
    ]
