# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lengthen_status_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='cross_listings',
        ),
        migrations.AlterField(
            model_name='advice',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='api.Offering'),
        ),
        migrations.AlterField(
            model_name='coursenumber',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_listings', to='api.Offering'),
        ),
        migrations.AlterField(
            model_name='coursenumber',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_numbers', to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.Offering'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='api.Section'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.Term'),
        ),
        migrations.AlterField(
            model_name='section',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.Offering'),
        ),
    ]
