# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_id_to_charfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursenumber',
            old_name='course',
            new_name='offering',
        ),
    ]
