# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_course_to_offering_in_cousenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='section name is invalid', regex='^[A-Z]\\d\\d[A-Z]?$')]),
        ),
    ]
